version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    tty: true
    environment:
      - SECRET_KEY=1bp2fs^s23jxt#yhvg$$1-)h$$02^hvl#u5zvg_zx7+vd9ug2t*#
      - DEBUG=True
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - ./postgres_data2:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
    - 5432:5432
volumes:
  postgres_data2: