"""Change a little password model

Revision ID: 5e2d1921f88e
Revises: 4c52f68d6eb7
Create Date: 2021-03-13 19:18:18.192018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2d1921f88e'
down_revision = '4c52f68d6eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('password', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('password', 'resource_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('password', 'resource_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('password', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
